export * from './pokemon.repository'
export * from './pokemonAbility.repository'
export * from './pokemonSprite.repository'
export * from './pokemonMove.repository'
export * from './pokemonType.repository'
